logging:
  level:
    org.springframework.security: DEBUG
    org.hibernate: DEBUG
    org.springframework.orm.jpa: DEBUG
spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/tokyo_spots?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=utf8
    username: mari
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true