logging:
  level:
    com.tato: DEBUG
    org.springframework.security: INFO
    org.hibernate: INFO
    org.springframework.orm.jpa: INFO


spring:
  thymeleaf:
    cache: false

  datasource:
    url: jdbc:mysql://localhost:3306/tokyo_spots?useSSL=false&serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf8
    username: mari
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true  #
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  mvc:
    hiddenmethod:
      filter:
        enabled: true

app:
  data:
    auto-load: false
  admin:
    auto-create: true
