logging:
  level:
    com.tato: DEBUG
    org.springframework.security: INFO
    org.hibernate: INFO
    org.springframework.orm.jpa: INFO

spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/tokyo_spots?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=utf8
    username: mari
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false  #로그 중복 방지 때문에
    properties:
      hibernate:
        format_sql: true

  mvc:
    hiddenmethod:
      filter:
        enabled: true

app:
  data:
    auto-load: true
  admin:
    auto-create: true